// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf-rFmqR2jFdIFGH3EZo08k48yLmdRMmk',
    appId: '1:86708810215:web:da5910d951d2a8c4a60d42',
    messagingSenderId: '86708810215',
    projectId: 'nurse-os',
    authDomain: 'nurse-os.firebaseapp.com',
    storageBucket: 'nurse-os.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmEoTgi48F6jhCYXUMamjLqXDwBVfLHrg',
    appId: '1:86708810215:android:514a9c9357e5f8f4a60d42',
    messagingSenderId: '86708810215',
    projectId: 'nurse-os',
    storageBucket: 'nurse-os.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPF7-gNElARHCXxo-G5fqjKSvuYQvB4Q',
    appId: '1:86708810215:ios:822cc9d829562373a60d42',
    messagingSenderId: '86708810215',
    projectId: 'nurse-os',
    storageBucket: 'nurse-os.firebasestorage.app',
    iosBundleId: 'com.nurseos.nurseosV3',
  );
}
